name: MensaUniurb
description: Check what's for launch from a beautiful app

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  firebase_admob: ^0.9.0+6
  flutter_launcher_icons: ^0.7.2+1
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  intl: ^0.16.0
  shared_preferences: ^0.5.3+1
  url_launcher: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Regular.ttf

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"
