name: MensaUniurb
description: Check what's for launch from this beautiful app

version: 1.2.1+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dynamic_theme: ^1.0.1
  flutter_launcher_icons: ^0.7.3
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  intl: ">=0.15.2"
  share: ^0.6.2+1
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Regular.ttf

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"
